name: ut_report_generator
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ^3.7.2

dependencies:
  desktop_updater: ^1.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
