name: ut_report_generator
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  easy_sticky_header: ^1.1.1
  file_picker: ^10.2.1
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_expandable_fab: ^2.5.2
  go_router: ^16.1.0
  http: ^1.4.0
  image_clipboard: ^1.1.0+1
  image_picker: ^1.2.0
  open_dir: ^0.0.2+1
  open_file: ^3.5.10
  provider: ^6.1.5
  relative_time: ^5.0.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
